#!/usr/bin/env python3
"""Install git hooks that enforce PRD reverse-sync discipline.

Currently provides a single hook:

- pre-push: when commits being pushed touch source code (controllers, schemas,
  routes, configs) but DO NOT touch any file under `docs/`, the hook prints a
  reverse-sync warning and exits non-zero. The user can override with the
  environment variable `ALLOW_DOC_SKIP=1` (the override is logged into
  `_test_output/reverse-sync-skip.log` so it surfaces in audit).

Usage:
    python scripts/install_git_hooks.py install --project-root .
    python scripts/install_git_hooks.py uninstall --project-root .

The hook itself is a portable shell script that delegates back to this Python
file via `python -m`-style invocation. We avoid Python on the hook hot-path so
it works on machines without Python on PATH but still keeps logic centralized.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

PRE_PUSH_HOOK_NAME = "pre-push"
HOOK_MARKER = "# software-development-team:reverse-sync-pre-push"

# These prefixes signal "real code change" that should be matched by a docs/ change.
CODE_PATH_PREFIXES = (
    "src/",
    "backend/",
    "frontend/",
    "app/",
    "server/",
    "db/",
    "migrations/",
    "prisma/",
    "config/",
)
CODE_PATH_SUFFIXES = (
    ".java", ".kt", ".scala",
    ".py",
    ".js", ".jsx", ".ts", ".tsx",
    ".vue",
    ".go", ".rs",
    ".sql",
    ".yaml", ".yml",
    ".properties",
)


def _git(args: list[str], cwd: Path) -> str:
    res = subprocess.run(
        ["git", *args], cwd=str(cwd), check=False,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    return res.stdout.strip()


def _hook_script_body(repo_root_marker: str) -> str:
    """Return the content of the pre-push hook script.

    The script reads stdin (git pre-push protocol) to discover the commit range,
    diffs it, and triggers the python-side check. It is intentionally simple so
    it works on git-bash (Windows), Linux and macOS without extra dependencies.
    """
    return f"""#!/usr/bin/env bash
{HOOK_MARKER}
# Auto-generated by scripts/install_git_hooks.py. Do not edit manually.

set -e

# Read pre-push stdin: <local_ref> <local_oid> <remote_ref> <remote_oid>
remote_oid=""
local_oid=""
while read local_ref local_sha remote_ref remote_sha; do
  local_oid="$local_sha"
  remote_oid="$remote_sha"
done

if [ -z "$local_oid" ] || [ "$local_oid" = "0000000000000000000000000000000000000000" ]; then
  exit 0
fi

if [ -z "$remote_oid" ] || [ "$remote_oid" = "0000000000000000000000000000000000000000" ]; then
  range="$local_oid"
  changed=$(git diff --name-only "$local_oid" 2>/dev/null || true)
else
  range="$remote_oid..$local_oid"
  changed=$(git diff --name-only "$range" 2>/dev/null || true)
fi

if [ -z "$changed" ]; then
  exit 0
fi

code_changed=0
docs_changed=0
while IFS= read -r f; do
  case "$f" in
    docs/*) docs_changed=1 ;;
  esac
  case "$f" in
    src/*|backend/*|frontend/*|app/*|server/*|db/*|migrations/*|prisma/*|config/*)
      code_changed=1 ;;
    *.java|*.py|*.js|*.jsx|*.ts|*.tsx|*.vue|*.go|*.rs|*.sql|*.kt|*.scala)
      code_changed=1 ;;
  esac
done <<< "$changed"

if [ "$code_changed" = "1" ] && [ "$docs_changed" = "0" ]; then
  if [ "${{ALLOW_DOC_SKIP:-0}}" = "1" ]; then
    mkdir -p _test_output
    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "{{\\"ts\\":\\"$ts\\",\\"range\\":\\"$range\\",\\"changedFiles\\":\\"$(echo "$changed" | tr '\\n' ',' )\\"}}" >> _test_output/reverse-sync-skip.log
    echo "[reverse-sync] WARNING: code-only push allowed via ALLOW_DOC_SKIP=1 (logged)."
    exit 0
  fi
  echo "" >&2
  echo "[reverse-sync] BLOCKED: code changed but docs/ untouched." >&2
  echo "  Range:    $range" >&2
  echo "  Workflow: references/reverse-sync-workflow.md" >&2
  echo "  Template: references/reverse-sync-template.md" >&2
  echo "" >&2
  echo "  Either back-fill docs/ (Path A / B / C of the workflow), or override:" >&2
  echo "    ALLOW_DOC_SKIP=1 git push ..." >&2
  exit 1
fi

exit 0
"""


def install(project_root: Path) -> int:
    git_dir = project_root / ".git"
    if not git_dir.is_dir():
        print(f"Not a git repository: {project_root}", file=sys.stderr)
        return 1
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / PRE_PUSH_HOOK_NAME

    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8", errors="ignore")
        if HOOK_MARKER not in existing:
            backup = hook_path.with_suffix(".pre-reverse-sync.bak")
            backup.write_text(existing, encoding="utf-8")
            print(f"Backed up existing hook to {backup}")

    hook_path.write_text(_hook_script_body(str(project_root)), encoding="utf-8", newline="\n")
    try:
        # Make executable on POSIX. On Windows this is a no-op but git-bash still runs it.
        os.chmod(hook_path, 0o755)
    except OSError:
        pass
    print(f"Installed pre-push reverse-sync hook at {hook_path}")
    return 0


def uninstall(project_root: Path) -> int:
    hook_path = project_root / ".git" / "hooks" / PRE_PUSH_HOOK_NAME
    if not hook_path.exists():
        print("No pre-push hook found.")
        return 0
    text = hook_path.read_text(encoding="utf-8", errors="ignore")
    if HOOK_MARKER not in text:
        print("Pre-push hook is not the reverse-sync hook; refusing to delete.")
        return 1
    hook_path.unlink()
    backup = hook_path.with_suffix(".pre-reverse-sync.bak")
    if backup.exists():
        hook_path.write_text(backup.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"Restored previous hook from {backup}")
    else:
        print("Removed reverse-sync pre-push hook.")
    return 0


def status(project_root: Path) -> int:
    hook_path = project_root / ".git" / "hooks" / PRE_PUSH_HOOK_NAME
    info = {
        "installed": hook_path.exists() and HOOK_MARKER in hook_path.read_text(encoding="utf-8", errors="ignore"),
        "path": str(hook_path),
        "checkedAt": datetime.now(timezone.utc).isoformat(),
    }
    print(json.dumps(info, ensure_ascii=False, indent=2))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["install", "uninstall", "status"])
    parser.add_argument("--project-root", default=".")
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve()
    if args.action == "install":
        return install(project_root)
    if args.action == "uninstall":
        return uninstall(project_root)
    return status(project_root)


if __name__ == "__main__":
    sys.exit(main())
